### ISSUE TITLE
Can't find deb repository

### ISSUE THREAD

**Issue by Alexey1100** [openss7/openss7#16]
I cannot find the link to the openss7 debian repos. There is no deb repos listed in `Repository Package Access` table in the user profile.

I've also checked the link from README: `http://www.openss7.org/repo/debs/debian/squeeze/amd64/main/openss7-repo_all.deb` -- it returns 404.

**Comment by bbidulock** [comment]
You can build your own debs with the github version.  If you really need binaries, you can always pay for them.  I stopped building binaries (except for specific clients) some years ago.  Anything on the openss7.org repo is mostly out of date.  Last build there was CentOS 6.4 I think.  The problem was that building and validating binary packages for multiple distros, releases, kernels, service packs, updates, ... (You get the idea?)  The only builds that I do that are not for clients are for Arch Linux (and in particular the unexicon spin).  There is an openss7 PKGBUILD on the Arch Linux AUR.

Maybe I should put this in the wiki or something?
