### ISSUE TITLE
OpenSS7 impossible install in Centos 6

### ISSUE THREAD

**Issue by XHAGBARD** [openss7/openss7#23]
Using autoconf to generate configure. **I get this output:**

configure.ac:139: warning: _OPENSS7_MISSING4 is m4_require'd but not m4_defun'd
m4/gcj.m4:452: _GCJ_TOOLS is expanded from...
m4/gcj.m4:441: _GCJ_CONFIG is expanded from...
m4/java.m4:189: _JAVA_SETUP_GCJ is expanded from...
m4/java.m4:80: _JAVA_SETUP is expanded from...
configure.ac:139: the top level
configure.ac:139: warning: _OPENSS7_MISSING4 is m4_require'd but not m4_defun'd
m4/java.m4:106: _JAVA_SETUP_JAR is expanded from...
m4/java.m4:80: _JAVA_SETUP is expanded from...
configure.ac:139: the top level
configure.ac:52: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:79: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:80: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:91: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:111: error: possibly undefined macro: AM_PROG_AS
configure.ac:112: error: possibly undefined macro: AM_PROG_AR
configure.ac:117: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:119: error: possibly undefined macro: AM_PROG_INSTALL_STRIP
configure.ac:135: error: possibly undefined macro: AM_PROG_GCJ
configure.ac:146: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:147: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:162: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:232: error: possibly undefined macro: AC_OPENSS7
configure:5453: error: possibly undefined macro: AC_MSG_WARN
configure:7055: error: possibly undefined macro: AC_LANG_FLAG

**I have all the prerequisites installed:**

Package bzip2-1.0.5-7.el6_0.x86_64 already installed and latest version
Package chkconfig-1.3.49.5-1.el6.x86_64 already installed and latest version
Package coreutils-8.4-43.el6.x86_64 already installed and latest version
Package createrepo-0.9.9-24.el6.noarch already installed and latest version
Package 1:doxygen-1.6.1-6.el6.x86_64 already installed and latest version
Package gcc-java-4.4.7-17.el6.x86_64 already installed and latest version
Package ghostscript-8.70-21.el6.x86_64 already installed and latest version
Package glibc-2.12-1.192.el6.x86_64 already installed and latest version
Package gnuplot-4.2.6-2.el6.x86_64 already installed and latest version
Package groff-1.18.1.4-21.el6.x86_64 already installed and latest version
Package gzip-1.3.12-22.el6.x86_64 already installed and latest version
Package ImageMagick-6.7.2.7-5.el6_8.x86_64 already installed and latest version
Package 1:java-1.6.0-openjdk-devel-1.6.0.40-1.13.12.6.el6_8.x86_64 already installed and latest version
Package 1:java-1.6.0-openjdk-javadoc-1.6.0.40-1.13.12.6.el6_8.x86_64 already installed and latest version
Package kernel-abi-whitelists-2.6.32-642.4.2.el6.noarch already installed and latest version
Package kernel-2.6.32-642.4.2.el6.x86_64 already installed and latest version
Package kernel-devel-2.6.32-642.4.2.el6.x86_64 already installed and latest version
Package latex2html-2008-4.el6.noarch already installed and latest version
Package libgcj-4.4.7-17.el6.x86_64 already installed and latest version
Package libgcj-devel-4.4.7-17.el6.x86_64 already installed and latest version
Package lsof-4.82-5.el6.x86_64 already installed and latest version
Package module-init-tools-3.9-25.el6.x86_64 already installed and latest version
Package 1:net-snmp-devel-5.5-57.el6_8.1.x86_64 already installed and latest version
Package 4:perl-devel-5.10.1-141.el6_7.1.x86_64 already installed and latest version
Package rpm-4.8.0-55.el6.x86_64 already installed and latest version
Package rpm-build-4.8.0-55.el6.x86_64 already installed and latest version
Package 1:tcl-devel-8.5.7-6.el6.x86_64 already installed and latest version
Package texlive-2007-60.el6_7.x86_64 already installed and latest version
Package texlive-dvips-2007-60.el6_7.x86_64 already installed and latest version
Package texlive-latex-2007-60.el6_7.x86_64 already installed and latest version
Package texlive-utils-2007-60.el6_7.x86_64 already installed and latest version
Package 1:transfig-3.2.5-10.el6.x86_64 already installed and latest version
Package xz-4.999.9-0.5.beta.20091007git.el6.x86_64 already installed and latest version
Package zip-3.0-1.el6_7.1.x86_64 already installed and latest version
Package kernel-devel-2.6.32-642.4.2.el6.x86_64 already installed and latest version
Package 1:net-snmp-5.5-57.el6_8.1.x86_64 already installed and latest version
Package 1:net-snmp-perl-5.5-57.el6_8.1.x86_64 already installed and latest version
Package 1:net-snmp-utils-5.5-57.el6_8.1.x86_64 already installed and latest version
Package lm_sensors-3.1.1-17.el6.x86_64 already installed and latest version
Package 1:net-snmp-devel-5.5-57.el6_8.1.x86_64 already installed and latest version
Package lm_sensors-devel-3.1.1-17.el6.x86_64 already installed and latest version
Package gcc-java-4.4.7-17.el6.x86_64 already installed and latest version
Package 1:java-1.6.0-openjdk-1.6.0.40-1.13.12.6.el6_8.x86_64 already installed and latest version
Package 1:java-1.6.0-openjdk-devel-1.6.0.40-1.13.12.6.el6_8.x86_64 already installed and latest version

**It is impossible to install the repository.**
[root@pruebas src]# rpm -ivh openss7-repo-1.1.7.20131209-1.el6.noarch.rpm 
Preparing...                ########################################### [100%]
error: %pre(openss7-repo-1.1.7.20131209-1.el6.noarch) scriptlet failed, exit status 1
error:   install: %pre scriptlet failed (2), skipping openss7-repo-1.1.7.20131209-1.el6

Any ideas?

**Comment by alegutier** [comment]
After a few weeks of tinkering with the source I was able to get this compiled on the 3.10 rhel7 kernel 
This is what I did. This is part of my spec file 

%prep
%setup -n %{name}-master

# Copying files necessary to allow openss7 to compile correctly,
# for some reason these files are no longer on the latest .zip file,
# but can be found on older version of openss7
# these files being copied from openss7-1.1.7.20131207.tar.xz
tar xvf %{SOURCE2}
%{__cp} -rpn ./%{openss7_base}/* .

# Linux Kernel 3.0+ has NF_HOOK function with 7 arguments,
# meanwhile openss7 calls for a return of NF_HOOK passing only six arguments
# via a process of elimination we determined which argument was ok to set to NULL
# openss7 is now compiling correctly on current kernel 3.10.0-327.el7.x86_64
# below we fix the arguments for the multiple c files depended on NF_HOOK

for i in np_ip.c np_udp.c udp.c rawip.c tcp.c sctp_output.c np_rtp.c sctp2.c sctp2.c.old ip.c ; do
sed -i -e 's/NF\_HOOK(PF\_INET\, NF\_IP\_LOCAL\_OUT\, skb\,/NF\_HOOK(PF\_INET\, NF\_IP\_LOCAL\_OUT\, NULL\, skb\,/g' ./src/drivers/$i
done

%build

#The package also does not come with a ./configure file and several things are missing, we had to do the following
aclocal --force -I ./m4
libtoolize --copy --force
autoheader --force
automake --add-missing --copy --force-missing --foreign
autoconf -d

# fix to allow kABI to be found by configure and removes warnings
sed -i -e '/\${rootdir}\/lib\/modules\/kabi\/kabi_whitelist_\${karch}/a \ \ \ \ \ \ \ \ \ \ \ \ \${rootdir}\/lib\/modules\/kabi-current\/kabi_whitelist_\${karch}' configure

# Variables and options remove several warnings regarding documentation requirements
# we had to use the without-libgcj option, since GCJ was deprecated on rhel/ol 7
# compile still needs a dummy variable for GCJ, otherwise it does not work.

LZMA_CMD=/usr/include/lzma \
GCJ=`ls -l1 /etc/alternatives/java | awk '{ print $11}'` \
./configure \
        --enable-autotest \
        --enable-silent-rules \
        --disable-java \
        --disable-docs \
        --disable-papers-print \
        --disable-papers-html \
        --disable-drafts \
        --prefix=/usr/local \
        --without-libgcj


Keep in mind  that this is a copy paste example from a spec file I wrote. That being said this is what is working for me . 

Cheers

**Comment by naeimi** [comment]
after these i get error in make V=0

> 
> `src/drivers/ip_hooks.h:726:2: error: #error Cannot tell how many arguments function __ip_select_ident() takes.
>  #error Cannot tell how many arguments function __ip_select_ident() takes.
>   ^
> src/drivers/np_ip.c: In function ‘np_ip_queue_xmit’:
> src/drivers/np_ip.c:1194:2: error: implicit declaration of function ‘ip_select_ident_more’ [-Werror=implicit-function-declaration]
>   ip_select_ident_more(iph, dst, NULL, 0);

any idea ?
`

**Comment by alegutier** [comment]
This is the same issue I was referring to with NF_HOOKS. See how the how many arguments are being passed and you may need to null a few if necessary. Make sure the numbers match when you call the function.

**Comment by sharktech46** [comment]
Alexandria, are you looking for a project? I am down in Pompano Beach looking for an openss7 programmer.

**Comment by alegutier** [comment]
@sharktech46 Thank you, but I am not a software developer. I am an unix admin for GE. I do have a background in C, but was mainly for writing drivers. I just had to get this running, since openss7 is a dependency for our software.

**Comment by sharktech46** [comment]
I understand but the offer is still valid. Experience with running openss7 is what I am also after.
Anton
920420sixnine44
