### ISSUE TITLE
Centos 6.4 specfs Permission denied on loading module

### ISSUE THREAD

**Issue by ocarriles** [openss7/openss7#7]
Hi Brian,

Using openss7-1.1.7-20131207 source release
it builds smoothly and clean
make install fails on openss7-modules:
reporting a KVERSION problem.

tweaking a bit openss7-modules script, I was able to make the full installation
but openss7 service refuse to run failing to load specfs module:

Loading Special Shadow Filesystem (specfs): FATAL: Error inserting specfs (/lib/modules/2.6.32-358.el6.x86_64/extra/openss7/specfs.ko): Permission denied
FATAL: Error running install command for specfs

With a bit of debugging I found that specs module is searching for a sort of md5 hash it cannot find.
Commented out strlock_load_check() call in strlock.c resolves that and module loads, but this time streams module panics the whole OS.

Your advice would be appreciated.
Thanks in advance for such a great job.

**Comment by bbidulock** [comment]
On CentOS you are better to bulid rpms rather than attempting a direct build and install.  Once you have built the rpms, just install them directly using rpm -ivvv.  Nevertheless, you will still likely need to sign on (free) to http://www.openss7.org/repo.html and provide username and password during install. You will also need to have your account enabled for enterprise systems (but email me your username and I'll do that).

Sorry for the trouble, but after I get time to push the Arch Linux builds the sign-on will no longer be necessary.

**Comment by ocarriles** [comment]
Thank you Brian for your prompt response.

My account is "ocarriles". I am able to login thru web page to my private profile.
Thanks in advance.

Oscar.
